accessing
errorObject: anError
	error:= anError